
### POST room
POST {{baase_url}}/api/v1/room
Content-Type: application/json
Client-Id: {{client_id}}
Authorization: Bearer {{bearer_token}}

{
  "configuration": {
    "asdasd": "asdas"
  },
  "title": "{{$random.alphabetic(10)}}",
  "createdBy": 1,
  "createdAt": "{{$isoTimestamp}}",
  "conversation": [],
  "parties": [
    1,
    2
  ]
}



### GET room
GET {{baase_url}}/api/v1/room
Content-Type: application/json
Client-Id: {{client_id}}
Authorization: Bearer {{bearer_token}}



### POST people
POST {{baase_url}}/api/v1/people
Content-Type: application/json
Client-Id: {{client_id}}
Authorization: Bearer {{bearer_token}}

{
  "name": "anas_11_",
  "type": "user" ,
  "gender": "male",
  "age": "16",
  "profilePic": "",
  "description": "",
  "metaData": {
    "anydata": "asd"
  }
}


### GET people
GET {{baase_url}}/api/v1/people
Content-Type: application/json
Client-Id: {{client_id}}
Authorization: Bearer {{bearer_token}}

### Update people
PATCH {{baase_url}}/api/v1/people/65a3358d9c2d1683df1290ec
Content-Type: application/json
Client-Id: {{client_id}}
Authorization: Bearer {{bearer_token}}

{
  "name_sdfg": "hazem  we1111",
  "gender": "male",
  "age": "16",
  "profilePic": "",
  "description": "",
  "credit": 100,
  "metaData": {
    "anydata": "asd"
  }
}



### POST conv. Template
POST {{baase_url}}/api/v1/room-template
Content-Type: application/json
Client-Id: {{client_id}}
Authorization: Bearer {{bearer_token}}

{
  "name": "مدرس الرياضيات",
  "description": "asd",
  "group": "الصف الأول",
  "groupSlug": "v1",
  "Prompt": "string",
  "defaultParties": [
    1,
    2
  ],
  "bots": [
    {
      "personTemplateId": "65a3358d9c2d1683df1290ec",
      "name": "lucy",
      "type": "bot",
      "gender": "female",
      "age": "16",
      "profilePic": "https://picsum.photos/id/497/200",
      "description": "",
      "metaData": {
        "anydata": "asd"
      }
    }
  ],
  "memory": "string",
  "metaData": {
    "any": "asd"
  }
}


### GET conv. Template
GET {{baase_url}}/api/v1/room-template
Content-Type: application/json
Client-Id: {{client_id}}
Authorization: Bearer {{bearer_token}}



### POST Chat
POST {{baase_url}}/api/v1/chat/65a33b1cf30544aeb150f209
Content-Type: application/json
Client-Id: {{client_id}}
Authorization: Bearer {{bearer_token}}

{
  "message": "hello again bot ",
  "name": "hazem",
  "role": "user",
  "metaData": {
    "anything": "asd"
  }
}
