
### POST room
POST {{baase_url}}/api/v1/room
Content-Type: application/json
Client-Id: {{client_id}}
Authorization: Bearer {{bearer_token}}

{
  "configuration": {
    "asdasd": "asdas"
  },
  "title": "{{$random.alphabetic(10)}}",
  "createdBy": 1,
  "createdAt": "{{$isoTimestamp}}",
  "conversation": [],
  "parties": [
    1,
    2
  ]
}



### GET room
GET {{baase_url}}/api/v1/room
Content-Type: application/json
Client-Id: {{client_id}}
Authorization: Bearer {{bearer_token}}



### POST people
POST {{baase_url}}/api/v1/people
Content-Type: application/json
Client-Id: {{client_id}}
Authorization: Bearer {{bearer_token}}

{
  "name": "anas_11_",
  "type": "user" ,
  "gender": "male",
  "age": "16",
  "profilePic": "",
  "description": "",
  "metaData": {
    "anydata": "asd"
  }
}


### GET people
GET {{baase_url}}/api/v1/people
Content-Type: application/json
Client-Id: {{client_id}}
Authorization: Bearer {{bearer_token}}

### Update people
PATCH {{baase_url}}/api/v1/people/65a3358d9c2d1683df1290ec
Content-Type: application/json
Client-Id: {{client_id}}
Authorization: Bearer {{bearer_token}}

{
  "name_sdfg": "hazem  we1111",
  "gender": "male",
  "age": "16",
  "profilePic": "",
  "description": "",
  "credit": 100,
  "metaData": {
    "anydata": "asd"
  }
}



### POST conv. Template
POST {{baase_url}}/api/v1/room-template
Content-Type: application/json
Client-Id: {{client_id}}
Authorization: Bearer {{bearer_token}}

{
  "name": "مدرس الرياضيات",
  "description": "asd",
  "group": "الصف الأول",
  "groupSlug": "v1",
  "Prompt": "string",
  "defaultParties": [
    1,
    2
  ],
  "bots": [
    {
      "personTemplateId": "65a3358d9c2d1683df1290ec",
      "name": "lucy",
      "type": "bot",
      "gender": "female",
      "age": "16",
      "profilePic": "https://picsum.photos/id/497/200",
      "description": "",
      "metaData": {
        "anydata": "asd"
      }
    }
  ],
  "memory": "string",
  "metaData": {
    "any": "asd"
  }
}


### GET conv. Template
GET {{baase_url}}/api/v1/room-template
Content-Type: application/json
Client-Id: {{client_id}}
Authorization: Bearer {{bearer_token}}



### POST Chat
POST {{baase_url}}/api/v1/chat/65a33b1cf30544aeb150f209
Content-Type: application/json
Client-Id: {{client_id}}
Authorization: Bearer {{bearer_token}}

{
  "message": "hello again bot ",
  "name": "hazem",
  "role": "user",
  "metaData": {
    "anything": "asd"
  }
}


###
# curl -L 'https://login.auth0.com/api/v2/rules
GET https://login.auth0.com/api/v2/rules
Authorization: Bearer {{bearer_token}}

###

### POST Chat
# curl --request POST
#  --url https://dev-d3kvtws4.us.auth0.com/oauth/token
#  --header 'content-type: application/json'
#  --data '{"client_id":"1klrs2xT6mXVduwkS1gRhmnEhp5yxNnQ","client_secret":"wQdNI3ASQ0RU5f9SMnId4GCyCvw0E5DZucUiFf2OLyCEj27y5wCQjW7224a5S5Qx","audience":"http://localhost:3000","grant_type":"client_credentials"}'
POST https://dev-d3kvtws4.us.auth0.com/oauth/token
Content-Type: application/json

{
  "client_id": "1klrs2xT6mXVduwkS1gRhmnEhp5yxNnQ",
  "client_secret": "wQdNI3ASQ0RU5f9SMnId4GCyCvw0E5DZucUiFf2OLyCEj27y5wCQjW7224a5S5Qx",
  "audience": "http://localhost:3000",
  "grant_type": "client_credentials"
}

###
# curl -L 'http://localhost:3000/users'
#-H 'Accept: application/json'
#-H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkhFV3J0d25pWW8xYjhUNzg1Wk85bCJ9.eyJpc3MiOiJodHRwczovL2Rldi1kM2t2dHdzNC51cy5hdXRoMC5jb20vIiwic3ViIjoiMWtscnMyeFQ2bVhWZHV3a1MxZ1JobW5FaHA1eXhOblFAY2xpZW50cyIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImlhdCI6MTcwNjMzNDQ4NSwiZXhwIjoxNzA2NDIwODg1LCJhenAiOiIxa2xyczJ4VDZtWFZkdXdrUzFnUmhtbkVocDV5eE5uUSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.x_XX61MIDbBu-ATQdgsTn3ra4zIFO3wIxJva5CQwLDoOTfb_ouxswOq5g8HLXlfWArLVrZk4CV3UDAaMfP_feYVg3V5CMMWzRh8c78bUB4MhpEo0LfJsx8vi_-UDnQgx2wcdDM5bKlCliaMGuQEkM2kcwJyZIXsAmCxXmfbZQCqtxVxOIVqZkRHK-Oc4EXMhJHgiwHBth9ShoIv04eghgbgWanD4jwk0jknwG4Rzcc41B7k7-qn7r6K6_RWn3pKxzuJoj7ATkxjOWK2WflF5eZWLK8xUBraKxEkmpSCBiqyMDA3vOYAciXHhimqSD4mmolTjp3id5lua_9lmF5NP0A'
GET https://dev-d3kvtws4.us.auth0.com/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkhFV3J0d25pWW8xYjhUNzg1Wk85bCJ9.eyJpc3MiOiJodHRwczovL2Rldi1kM2t2dHdzNC51cy5hdXRoMC5jb20vIiwic3ViIjoiMWtscnMyeFQ2bVhWZHV3a1MxZ1JobW5FaHA1eXhOblFAY2xpZW50cyIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImlhdCI6MTcwNjMzNDQ4NSwiZXhwIjoxNzA2NDIwODg1LCJhenAiOiIxa2xyczJ4VDZtWFZkdXdrUzFnUmhtbkVocDV5eE5uUSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.x_XX61MIDbBu-ATQdgsTn3ra4zIFO3wIxJva5CQwLDoOTfb_ouxswOq5g8HLXlfWArLVrZk4CV3UDAaMfP_feYVg3V5CMMWzRh8c78bUB4MhpEo0LfJsx8vi_-UDnQgx2wcdDM5bKlCliaMGuQEkM2kcwJyZIXsAmCxXmfbZQCqtxVxOIVqZkRHK-Oc4EXMhJHgiwHBth9ShoIv04eghgbgWanD4jwk0jknwG4Rzcc41B7k7-qn7r6K6_RWn3pKxzuJoj7ATkxjOWK2WflF5eZWLK8xUBraKxEkmpSCBiqyMDA3vOYAciXHhimqSD4mmolTjp3id5lua_9lmF5NP0A

###




###


###

